version: '3'
services:
  app:
    image: node:10
    ports:
      - 4200:4200
      - 80:8080
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
